aliyun/credentials-java

.scrutinizer.yml
README-CN.md
README.md

addScrutinizer _case

---

src/test/java/provider/ECSMetadataServiceCredentialsFetcherTest.java
src/test/java/provider/ProfileCredentialsProviderTest.java

improve tests

---

.scrutinizer.yml

improved tests

---

src/main/java/com/aliyun/credentials/http/CompatibleUrlConnClient.java
src/main/java/com/aliyun/credentials/provider/DefaultCredentialsProvider.java
src/main/java/com/aliyun/credentials/provider/RamRoleArnCredentialProvider.java
src/test/java/function/HttpClientTest.java
src/test/java/http/CompatibleUrlConnClientTest.java

change logic and test

---

.travis.yml
pom.xml

release version 0.0.1

---

ChangeLog.txt
pom.xml

release version 0.0.2

---

ChangeLog.txt
pom.xml
src/main/java/com/aliyun/credentials/Client.java
src/main/java/com/aliyun/credentials/Credential.java
src/test/java/CredentialTest.java

release version 0.1.2

---

README-CN.md
README.md
src/main/java/com/aliyun/credentials/Client.java
src/main/java/com/aliyun/credentials/models/Config.java
src/main/java/com/aliyun/credentials/provider/RamRoleArnCredentialProvider.java

improve credentials

---

src/main/java/com/aliyun/credentials/EcsRamRoleCredential.java
src/main/java/com/aliyun/credentials/RamRoleArnCredential.java
src/main/java/com/aliyun/credentials/RsaKeyPairCredential.java
src/main/java/com/aliyun/credentials/provider/ECSMetadataServiceCredentialsFetcher.java
src/main/java/com/aliyun/credentials/provider/EcsRamRoleCredentialProvider.java
src/main/java/com/aliyun/credentials/utils/RefreshUtils.java
src/test/java/EcsRamRoleCredentialTest.java
src/test/java/RamRoleArnCredentialTest.java
src/test/java/RsaKeyPairCredentialTest.java
src/test/java/provider/ECSMetadataServiceCredentialsFetcherTest.java
src/test/java/provider/EcsRamRoleCredentialProviderTest.java
src/test/java/utils/RefreshUtilsTest.java

add refreshCredential

---

ChangeLog.txt
pom.xml

release version 0.2.2

---

ChangeLog.txt
pom.xml
src/test/java/provider/ECSMetadataServiceCredentialsFetcherTest.java
src/test/java/provider/EcsRamRoleCredentialProviderTest.java
src/test/java/provider/RamRoleArnCredentialProviderTest.java
src/test/java/provider/RsaKeyPairCredentialProviderTest.java

release version 0.2.3

---

ChangeLog.txt
pom.xml

release version 0.2.5

---

README.md

change api explorer to workbench

---

README-CN.md

change explorer to workbench

---

README-CN.md
README.md
src/main/java/com/aliyun/credentials/Client.java
src/main/java/com/aliyun/credentials/Configuration.java
src/main/java/com/aliyun/credentials/Credential.java
src/main/java/com/aliyun/credentials/OIDCRoleArnCredential.java
src/main/java/com/aliyun/credentials/URLCredential.java
src/main/java/com/aliyun/credentials/models/Config.java
src/main/java/com/aliyun/credentials/provider/OIDCRoleArnCredentialProvider.java
src/main/java/com/aliyun/credentials/provider/ProfileCredentialsProvider.java
src/main/java/com/aliyun/credentials/provider/RamRoleArnCredentialProvider.java
src/main/java/com/aliyun/credentials/provider/URLCredentialProvider.java
src/main/java/com/aliyun/credentials/utils/AuthConstant.java
src/main/java/com/aliyun/credentials/utils/AuthUtils.java
src/test/java/OIDCRoleArnCredentialTest.java
src/test/java/URLCredentialTest.java
src/test/java/provider/OIDCRoleArnCredentialProviderTest.java
src/test/java/provider/ProfileCredentialsProviderTest.java
src/test/java/provider/URLCredentialProviderTest.java
src/test/resources/OIDCToken.txt

support AssumeRoleWithOIDC

---

ChangeLog.txt
pom.xml

release version 0.2.6

---

README-CN.md
README.md
src/main/java/com/aliyun/credentials/http/CompatibleUrlConnClient.java
src/main/java/com/aliyun/credentials/provider/OIDCRoleArnCredentialProvider.java
src/main/java/com/aliyun/credentials/provider/ProfileCredentialsProvider.java
src/main/java/com/aliyun/credentials/provider/URLCredentialProvider.java
src/test/java/provider/OIDCRoleArnCredentialProviderTest.java
src/test/java/provider/ProfileCredentialsProviderTest.java
src/test/java/provider/URLCredentialProviderTest.java

change AssumeRoleWithOIDC request method

---

ChangeLog.txt
README-CN.md
README.md
pom.xml

release version

---

src/main/java/com/aliyun/credentials/provider/OIDCRoleArnCredentialProvider.java
src/main/java/com/aliyun/credentials/provider/RamRoleArnCredentialProvider.java
src/test/java/provider/OIDCRoleArnCredentialProviderTest.java
src/test/java/provider/RamRoleArnCredentialProviderTest.java

support roleSessionName for config

---

ChangeLog.txt
pom.xml

release version 0.2.8

---

.github/workflows/ci.yml
src/main/java/com/aliyun/credentials/utils/RefreshUtils.java
src/test/java/function/HttpClientTest.java
src/test/java/http/CompatibleUrlConnClientTest.java
src/test/java/provider/DefaultCredentialsProviderTest.java

fix refresh failure caused by time slot

---

src/main/java/com/aliyun/credentials/Client.java
src/main/java/com/aliyun/credentials/Configuration.java
src/main/java/com/aliyun/credentials/models/Config.java
src/main/java/com/aliyun/credentials/provider/OIDCRoleArnCredentialProvider.java
src/main/java/com/aliyun/credentials/provider/RamRoleArnCredentialProvider.java
src/main/java/com/aliyun/credentials/provider/RsaKeyPairCredentialProvider.java
src/test/java/ConfigurationTest.java
src/test/java/provider/OIDCRoleArnCredentialProviderTest.java
src/test/java/provider/RamRoleArnCredentialProviderTest.java
src/test/java/provider/RsaKeyPairCredentialProviderTest.java

support user-defined sts endpoint

---

src/main/java/com/aliyun/credentials/Client.java
src/test/java/ClientTest.java

feat: assign provider to credentials

---

src/main/java/com/aliyun/credentials/provider/EnvironmentVariableCredentialsProvider.java
src/main/java/com/aliyun/credentials/utils/AuthUtils.java
src/test/java/provider/EnvironmentVariableCredentialsProviderTest.java

feat: support env ALIBABA_CLOUD_SECURITY_TOKEN

---

src/main/java/com/aliyun/credentials/Client.java
src/main/java/com/aliyun/credentials/http/FormatType.java
src/main/java/com/aliyun/credentials/models/Config.java
src/main/java/com/aliyun/credentials/provider/DefaultCredentialsProvider.java
src/main/java/com/aliyun/credentials/provider/ECSMetadataServiceCredentialsFetcher.java
src/main/java/com/aliyun/credentials/provider/EcsRamRoleCredentialProvider.java
src/main/java/com/aliyun/credentials/utils/AuthUtils.java
src/test/java/function/HttpClientTest.java
src/test/java/models/ConfigTest.java
src/test/java/provider/ECSMetadataServiceCredentialsFetcherTest.java
src/test/java/utils/AuthUtilsTest.java

feat: support IMDSv2 for ECS metadata

---

.github/workflows/ci.yml

see: https://www.oracle.com/java/technologies/java-se-support-roadmap.html

just run test cases on LTS versions

---

.github/workflows/ci.yml

test: fix coverage upload

---

.gitignore
src/main/java/com/aliyun/credentials/exception/CredentialException.java
src/main/java/com/aliyun/credentials/http/X509TrustManagerImp.java
src/test/java/AccessKeyCredentialTest.java
src/test/java/ClientTest.java
src/test/java/OIDCRoleArnCredentialTest.java
src/test/java/http/X509TrustManagerImpTest.java
src/test/java/provider/ECSMetadataServiceCredentialsFetcherTest.java
src/test/java/provider/URLCredentialProviderTest.java

cleanup unused imports

---

src/main/java/com/aliyun/credentials/provider/OIDCRoleArnCredentialProvider.java
src/main/java/com/aliyun/credentials/provider/RamRoleArnCredentialProvider.java
src/main/java/com/aliyun/credentials/provider/RsaKeyPairCredentialProvider.java

Cleanup useless regionId

---

src/main/java/com/aliyun/credentials/provider/OIDCRoleArnCredentialProvider.java
src/test/java/com/aliyun/credentials/provider/OIDCRoleArnCredentialProviderTest.java

cleanup useless ak

---

src/test/java/com/aliyun/credentials/models/CredentialModelTest.java
src/test/java/com/aliyun/credentials/utils/AuthConstantTest.java

improve test coverage

---

src/main/java/com/aliyun/credentials/http/CompatibleUrlConnClient.java
src/test/java/com/aliyun/credentials/http/CompatibleUrlConnClientTest.java

fix: transfer all request headers into connection property

---

pom.xml
src/main/java/com/aliyun/credentials/http/CompatibleUrlConnClient.java
src/main/resources/version.properties
src/test/java/com/aliyun/credentials/http/CompatibleUrlConnClientTest.java

feat: add user-agent for all credential requests

---

README-CN.md
README.md

remove the description of rsakeypair

---

src/main/java/com/aliyun/credentials/models/Config.java
src/test/java/com/aliyun/credentials/models/ConfigTest.java

fix: update timeout for all credential requests

---

pom.xml
src/main/java/com/aliyun/credentials/http/CompatibleUrlConnClient.java

fix: update hostname verifier

---

src/main/java/com/aliyun/credentials/Client.java
src/main/java/com/aliyun/credentials/models/Config.java
src/main/java/com/aliyun/credentials/provider/ECSMetadataServiceCredentialsFetcher.java
src/main/java/com/aliyun/credentials/provider/EcsRamRoleCredentialProvider.java
src/main/java/com/aliyun/credentials/utils/AuthUtils.java
src/test/java/com/aliyun/credentials/models/ConfigTest.java
src/test/java/com/aliyun/credentials/provider/ECSMetadataServiceCredentialsFetcherTest.java
src/test/java/com/aliyun/credentials/utils/AuthUtilsTest.java

feat: support imds v2 default for ecs ram role

---

src/main/java/com/aliyun/credentials/Client.java
src/main/java/com/aliyun/credentials/provider/RamRoleArnCredentialProvider.java
src/test/java/com/aliyun/credentials/ClientTest.java
src/test/java/com/aliyun/credentials/provider/RamRoleArnCredentialProviderTest.java

feat: support inner credentials provider for RAM role arn

---

src/main/java/com/aliyun/credentials/Client.java
src/main/java/com/aliyun/credentials/URLCredential.java
src/main/java/com/aliyun/credentials/provider/DefaultCredentialsProvider.java
src/main/java/com/aliyun/credentials/provider/ECSMetadataServiceCredentialsFetcher.java
src/main/java/com/aliyun/credentials/provider/EnvironmentVariableCredentialsProvider.java
src/main/java/com/aliyun/credentials/provider/OIDCRoleArnCredentialProvider.java
src/main/java/com/aliyun/credentials/provider/ProfileCredentialsProvider.java
src/main/java/com/aliyun/credentials/provider/RamRoleArnCredentialProvider.java
src/main/java/com/aliyun/credentials/provider/RefreshCachedSupplier.java
src/main/java/com/aliyun/credentials/provider/RsaKeyPairCredentialProvider.java
src/main/java/com/aliyun/credentials/provider/SystemPropertiesCredentialsProvider.java
src/main/java/com/aliyun/credentials/provider/URLCredentialProvider.java
src/main/java/com/aliyun/credentials/utils/AuthConstant.java
src/main/java/com/aliyun/credentials/utils/AuthUtils.java
src/test/java/com/aliyun/credentials/ClientTest.java
src/test/java/com/aliyun/credentials/CredentialTest.java
src/test/java/com/aliyun/credentials/URLCredentialTest.java
src/test/java/com/aliyun/credentials/http/HttpRequestTest.java
src/test/java/com/aliyun/credentials/provider/CLIProfileCredentialsProviderTest.java
src/test/java/com/aliyun/credentials/provider/DefaultCredentialsProviderTest.java
src/test/java/com/aliyun/credentials/provider/ECSMetadataServiceCredentialsFetcherTest.java
src/test/java/com/aliyun/credentials/provider/EnvironmentVariableCredentialsProviderTest.java
src/test/java/com/aliyun/credentials/provider/OIDCRoleArnCredentialProviderTest.java
src/test/java/com/aliyun/credentials/provider/ProfileCredentialsProviderTest.java
src/test/java/com/aliyun/credentials/provider/RamRoleArnCredentialProviderTest.java
src/test/java/com/aliyun/credentials/provider/RsaKeyPairCredentialProviderTest.java
src/test/java/com/aliyun/credentials/provider/SystemPropertiesCredentialsProviderTest.java
src/test/java/com/aliyun/credentials/provider/URLCredentialProviderTest.java

improve exception handling

---

src/main/java/com/aliyun/credentials/Client.java
src/main/java/com/aliyun/credentials/provider/DefaultCredentialsProvider.java
src/main/java/com/aliyun/credentials/provider/ECSMetadataServiceCredentialsFetcher.java
src/main/java/com/aliyun/credentials/provider/EcsRamRoleCredentialProvider.java
src/test/java/com/aliyun/credentials/ClientTest.java
src/test/java/com/aliyun/credentials/provider/DefaultCredentialsProviderTest.java
src/test/java/com/aliyun/credentials/provider/ECSMetadataServiceCredentialsFetcherTest.java
src/test/java/com/aliyun/credentials/provider/EcsRamRoleCredentialProviderTest.java
src/test/java/com/aliyun/credentials/utils/AuthUtilsTest.java

refactor: get metadata token every time refresh credentials

---

src/main/java/com/aliyun/credentials/provider/CLIProfileCredentialsProvider.java
src/test/java/com/aliyun/credentials/provider/CLIProfileCredentialsProviderTest.java
src/test/resources/.aliyun/config.json

feat: support StsToken mode in cli profile
